# Generated by Django 5.2.13 on 2026-04-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='update_arduino',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machinestate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
