# Generated by Django 5.2.13 on 2026-04-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machinestate_update_arduino_alter_machinestate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinestate',
            old_name='update_arduino',
            new_name='arduino_connected',
        ),
    ]
