# Generated by Django 5.2.13 on 2026-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_rename_update_arduino_machinestate_arduino_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='speed_motor_roda',
            field=models.IntegerField(default=0),
        ),
    ]
