# Generated by Django 6.0.4 on 2026-04-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_machinestate_speed_motor_roda'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='lateral_misalignment_current',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machinestate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
