# Generated by Django 5.2.13 on 2026-05-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_machinestate_lateral_misalignment_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinestate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
