# Generated by Django 6.0.4 on 2026-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_alter_machinestate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='motor_turns_per_wheel_turn',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_direction',
            field=models.CharField(default='stopped', max_length=30),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_position_degrees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_total_turns',
            field=models.FloatField(default=0),
        ),
    ]
