# Generated by Django 6.0.4 on 2026-05-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_machinestate_motor_turns_per_wheel_turn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuração principal', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Define se esta configuração é a configuração ativa da máquina.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_baudrate', models.IntegerField(default=9600, help_text='Velocidade de comunicação serial com o Arduino.')),
                ('wheel_total_spokes', models.IntegerField(default=36, help_text='Quantidade total de raios da roda. Exemplo: 36.')),
                ('motor_steps_per_wheel_turn', models.IntegerField(default=6400, help_text='Quantidade de passos do motor para a roda dar uma volta completa.')),
                ('motor_steps_per_motor_turn', models.IntegerField(default=200, help_text='Quantidade de passos do motor para uma volta do próprio eixo.')),
                ('motor_microsteps', models.IntegerField(default=1, help_text='Configuração de micro passos usada no driver do motor.')),
                ('motor_turns_per_wheel_turn', models.FloatField(default=1, help_text='Quantidade de voltas do motor para a roda dar uma volta completa.')),
                ('motor_max_speed', models.FloatField(default=1000, help_text='Velocidade máxima do motor usada no Arduino.')),
                ('motor_acceleration', models.FloatField(default=500, help_text='Aceleração do motor usada no Arduino.')),
                ('motor_step_pin', models.IntegerField(default=2, help_text='Pino STEP do driver do motor da roda.')),
                ('motor_dir_pin', models.IntegerField(default=3, help_text='Pino DIR do driver do motor da roda.')),
                ('motor_enable_pin', models.IntegerField(default=4, help_text='Pino ENABLE do driver do motor da roda.')),
                ('lateral_sensor_pin', models.CharField(default='A0', help_text='Pino analógico usado pelo sensor lateral. Exemplo: A0.', max_length=10)),
                ('lateral_sensor_zero_offset', models.FloatField(default=0, help_text='Offset de calibração do sensor lateral em milímetros.')),
                ('lateral_sensor_dead_zone', models.FloatField(default=0, help_text='Zona morta do sensor lateral em milímetros.')),
                ('led_pin', models.IntegerField(default=13, help_text='Pino usado para LED de teste/status.')),
            ],
            options={
                'verbose_name': 'Configuração da máquina',
                'verbose_name_plural': 'Configurações da máquina',
            },
        ),
    ]
