# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_machineconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='wheel_current_angle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_target_angle',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_current_spoke',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_target_spoke',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_total_spokes',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='wheel_is_positioning',
            field=models.BooleanField(default=False),
        ),
    ]
