# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_machinestate_wheel_position_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='spoke_tension_left_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='spoke_tension_right_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='is_spoke_tension_collecting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='spoke_tension_left_dout_pin',
            field=models.IntegerField(
                default=3,
                help_text='Pino DT/DOUT do HX711 do lado esquerdo.',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='spoke_tension_left_sck_pin',
            field=models.IntegerField(
                default=2,
                help_text='Pino SCK/CLK do HX711 do lado esquerdo.',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='spoke_tension_right_dout_pin',
            field=models.IntegerField(
                default=5,
                help_text='Pino DT/DOUT do HX711 do lado direito.',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='spoke_tension_right_sck_pin',
            field=models.IntegerField(
                default=4,
                help_text='Pino SCK/CLK do HX711 do lado direito.',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='spoke_tension_left_calibration_factor',
            field=models.FloatField(
                default=-7050,
                help_text='Fator de calibração do HX711 esquerdo.',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='spoke_tension_right_calibration_factor',
            field=models.FloatField(
                default=-7050,
                help_text='Fator de calibração do HX711 direito.',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='spoke_tension_read_interval_ms',
            field=models.IntegerField(
                default=80,
                help_text='Intervalo de leitura/envio dos HX711 em milissegundos.',
            ),
        ),
    ]
