# Generated by Codex on 2026-05-20

from django.db import migrations, models


def update_existing_spoke_tension_config(apps, schema_editor):
    MachineConfig = apps.get_model('machine', 'MachineConfig')

    MachineConfig.objects.update(
        spoke_tension_left_dout_pin=3,
        spoke_tension_left_sck_pin=2,
        spoke_tension_right_dout_pin=5,
        spoke_tension_right_sck_pin=4,
        spoke_tension_left_calibration_factor=-7050,
        spoke_tension_right_calibration_factor=-7050,
        spoke_tension_read_interval_ms=80,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0011_spoke_tension_hx711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineconfig',
            name='spoke_tension_left_dout_pin',
            field=models.IntegerField(
                default=3,
                help_text='Pino DT/DOUT do HX711 do lado esquerdo.',
                verbose_name='Pino DOUT esquerdo',
            ),
        ),
        migrations.AlterField(
            model_name='machineconfig',
            name='spoke_tension_left_sck_pin',
            field=models.IntegerField(
                default=2,
                help_text='Pino SCK/CLK do HX711 do lado esquerdo.',
                verbose_name='Pino SCK esquerdo',
            ),
        ),
        migrations.AlterField(
            model_name='machineconfig',
            name='spoke_tension_right_dout_pin',
            field=models.IntegerField(
                default=5,
                help_text='Pino DT/DOUT do HX711 do lado direito.',
                verbose_name='Pino DOUT direito',
            ),
        ),
        migrations.AlterField(
            model_name='machineconfig',
            name='spoke_tension_right_sck_pin',
            field=models.IntegerField(
                default=4,
                help_text='Pino SCK/CLK do HX711 do lado direito.',
                verbose_name='Pino SCK direito',
            ),
        ),
        migrations.AlterField(
            model_name='machineconfig',
            name='spoke_tension_left_calibration_factor',
            field=models.FloatField(
                default=-7050,
                help_text='Fator de calibração do HX711 esquerdo.',
                verbose_name='Fator de calibração esquerdo',
            ),
        ),
        migrations.AlterField(
            model_name='machineconfig',
            name='spoke_tension_right_calibration_factor',
            field=models.FloatField(
                default=-7050,
                help_text='Fator de calibração do HX711 direito.',
                verbose_name='Fator de calibração direito',
            ),
        ),
        migrations.AlterField(
            model_name='machineconfig',
            name='spoke_tension_read_interval_ms',
            field=models.IntegerField(
                default=80,
                help_text='Intervalo de leitura/envio dos HX711 em milissegundos.',
                verbose_name='Intervalo de leitura em ms',
            ),
        ),
        migrations.RunPython(
            update_existing_spoke_tension_config,
            migrations.RunPython.noop,
        ),
    ]
