# Generated by Django 5.2.13 on 2026-05-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0012_fix_spoke_tension_admin_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinestate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
