# Generated by Django 6.0.4 on 2026-05-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0013_alter_machineconfig_id_alter_machinestate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinestate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
