# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0014_alter_machineconfig_id_alter_machinestate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineconfig',
            name='pneumatic_spoke_tension_left_pin',
            field=models.IntegerField(
                default=22,
                help_text='Pino da valvula solenoide do cilindro de tensao esquerdo.',
                verbose_name='Cilindro tensao esquerdo',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='pneumatic_spoke_tension_right_pin',
            field=models.IntegerField(
                default=23,
                help_text='Pino da valvula solenoide do cilindro de tensao direito.',
                verbose_name='Cilindro tensao direito',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='pneumatic_nipple_arm_left_pin',
            field=models.IntegerField(
                default=24,
                help_text='Pino da valvula do avanco horizontal esquerdo do mecanismo do niple.',
                verbose_name='Cilindro avanco horizontal esquerdo',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='pneumatic_nipple_arm_right_pin',
            field=models.IntegerField(
                default=25,
                help_text='Pino da valvula do avanco horizontal direito do mecanismo do niple.',
                verbose_name='Cilindro avanco horizontal direito',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='pneumatic_nipple_lift_left_pin',
            field=models.IntegerField(
                default=26,
                help_text='Pino da valvula do cilindro vertical esquerdo do mecanismo do niple.',
                verbose_name='Cilindro sobe/desce esquerdo',
            ),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='pneumatic_nipple_lift_right_pin',
            field=models.IntegerField(
                default=27,
                help_text='Pino da valvula do cilindro vertical direito do mecanismo do niple.',
                verbose_name='Cilindro sobe/desce direito',
            ),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='pneumatic_spoke_tension_left_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='pneumatic_spoke_tension_right_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='pneumatic_nipple_arm_left_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='pneumatic_nipple_arm_right_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='pneumatic_nipple_lift_left_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinestate',
            name='pneumatic_nipple_lift_right_extended',
            field=models.BooleanField(default=False),
        ),
    ]
